-- 코드를 입력하세요
SELECT 
    B.USER_ID,
    B.NICKNAME,
    CONCAT(B.CITY, ' ', B.STREET_ADDRESS1, ' ', B.STREET_ADDRESS2) AS '전체주소',
    CONCAT(
        INSERT(INSERT(B.TLNO, 4, 0, '-'), 9, 0, '-')
    ) AS '전화번호'
FROM USED_GOODS_BOARD A 
    INNER JOIN USED_GOODS_USER B ON A.WRITER_ID = B.USER_ID
WHERE B.USER_ID IN (
        SELECT WRITER_ID 
        FROM USED_GOODS_BOARD
        GROUP BY WRITER_ID
        HAVING COUNT(*) >= 3
    )
GROUP BY B.USER_ID
ORDER BY B.USER_ID DESC;
